# This file was automatically generated by Shore. Do not edit manually.
# For more information on Shore see https://pypi.org/project/nr.shore/

import io
import re
import setuptools
import sys

with io.open('lib/c4ddev/__init__.py', encoding='utf8') as fp:
  version = re.search(r"__version__\s*=\s*'(.*)'", fp.read()).group(1)

with io.open('README.md', encoding='utf8') as fp:
  long_description = fp.read()

requirements = ['beautifulsoup4 >=4.6.0,<5.0.0', 'click >=6.7', 'nr.parsing.core >=0.0.1,<0.1.0', 'requests >=2.19.1,<3.0.0', 'six >=1.11.0,<2.0.0']

setuptools.setup(
  name = 'c4ddev',
  version = version,
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'C4DDev is a set of command-line tools and Cinema 4D plugins to make development plugins easier.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = 'https://github.com/NiklasRosenstein/c4ddev',
  license = 'MIT',
  packages = setuptools.find_packages('lib', ['test', 'test.*', 'docs', 'docs.*']),
  package_dir = {'': 'lib'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = None, # TODO: '>=2.7,<3.0.0 | >=3.4,<4.0.0',
  data_files = [],
  entry_points = {
    'console_scripts': [
      'c4ddev = c4ddev.__main__:main',
    ]
  },
  cmdclass = {},
  keywords = [],
  classifiers = [],
)
