# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

command = sys.argv[1] if len(sys.argv) >= 2 else None

readme_file = 'README.md'
if os.path.isfile(readme_file):
  with io.open(readme_file, encoding='utf8') as fp:
    long_description = fp.read()
else:
  print("warning: file \"{}\" does not exist.".format(readme_file), file=sys.stderr)
  long_description = None

requirements = [
  'beautifulsoup4 >=4.6.0,<5.0.0',
  'click >=6.7.0',
  'nr.parsing.core >=0.0.1,<0.1.0',
  'requests >=2.19.1,<3.0.0',
  'six >=1.11.0,<2.0.0',
]

setuptools.setup(
  name = 'c4ddev',
  version = '1.7.1',
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'C4DDev is a set of command-line tools and Cinema 4D plugins to make development plugins easier.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = 'https://github.com/NiklasRosenstein/c4ddev',
  license = 'MIT',
  packages = setuptools.find_packages('lib', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'lib'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = None,  # '>=2.7,<3.0.0 | >=3.4,<4.0.0',
  data_files = [],
  entry_points = {
    'console_scripts': [
      'c4ddev = c4ddev.__main__:main',
    ]
  },
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = True,
  options = {
    'bdist_wheel': {
      'universal': True,
    },
  },
)
