// C4D-DialogResource
DIALOG DRAWHELPER_EDITOR
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC; SCALE_V; SCALE_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 8, 4, 8, 8; 
    COLUMNS 1;
    
    BUTTON BTN_COMMIT { NAME IDS_BUTTON; ALIGN_TOP; ALIGN_LEFT; SIZE 65, 15; }
    MULTILINEEDIT EDT_SOURCE
    { 
      SCALE_V; SCALE_H; SIZE 70, 0; 
      MONOSPACED; SYNTAXCOLOR; PYTHON; STATUSBAR; }
  }
}